#!/bin/sh
#
#      Jonathan Perkin <jonathan@perkin.org.uk> wrote this file.
#
# You can freely distribute/modify it (and are encouraged to do so),
# and you are welcome to buy me a beer if we ever meet and you think
# this stuff is worth it.  Improvements and cleanups always welcome.
#
# scripts/mutt/seteditor - set up the editor for a specific mail in mutt
#


case "${EDITOR}" in
vim)
    ARGS="-X -c 'set tw=$1 autoindent syntax=mail' '+/^$'"
    ;;
esac

echo "set editor=\"${EDITOR} ${ARGS}\""
