#!/bin/sh
#
#      Jonathan Perkin <jonathan@perkin.org.uk> wrote this file.
#
# You can freely distribute/modify it (and are encouraged to do so),
# and you are welcome to buy me a beer if we ever meet and you think
# this stuff is worth it.  Improvements and cleanups always welcome.
#
# etc/sh/basicenv - essential environment variables.
#


# Basic environment setup

# Dig out various details of the local environment, used to correctly
# configure our setup.
OS_NAME=`uname -s`

case "${OS_NAME}" in
Linux)
    # Use the same as pkgsrc for consistency, as well as the fact that
    # `uname -p' on Linux usually returns "unknown".
    OS_ARCH=`uname -m | sed -e 's/i.86/i386/' -e 's/ppc/powerpc/'`

    # Given the frequent nature of Linux kernel revisions compared to
    # other operating systems, use the major release only as opposed to
    # the full version to save us having hundreds of individual builds.
    OS_VERSION=`uname -r | cut -d. -f1-2`
    ;;
OpenBSD)
    # OpenBSD returns CPU identification string in `uname -p`
    OS_ARCH=`uname -m`
    OS_VERSION=`uname -r`
    ;;
*)
    OS_ARCH=`uname -p`
    OS_VERSION=`uname -r`
    ;;
esac

OS_HOST=`hostname`

OS_PREFIX=${OS_NAME}-${OS_VERSION}-${OS_ARCH}

export OS_ARCH OS_HOST OS_NAME OS_PREFIX OS_VERSION
