#!/bin/sh
#
#      Jonathan Perkin <jonathan@perkin.org.uk> wrote this file.
#
# You can freely distribute/modify it (and are encouraged to do so),
# and you are welcome to buy me a beer if we ever meet and you think
# this stuff is worth it.  Improvements and cleanups always welcome.
#
# .lbdb/lbdbrc - configuration file for the Little Brother DataBase.
#


#
# This is just a sourced shell script so we use some existing variables
# to set our preferred order of search databases, based upon their
# existance.
# 
for m in m_abook m_osx_addressbook; do
    if [ -f ${libdir}/${m} ]; then
        METHODS="${METHODS} ${m}"
    fi
done
